export const testimonialDataThree = [
    {
        id: 1,
        name: "Andre Muscat",
        src: '/images/testimonial/client-img-3-1.png',
        position: "Businessman",
        review: "Support was very well organised, and responses were well received within 24 hours each time. The only point where I think they can do better is having a more detailed help area.",
        title:"Customer Support",
        rating: 5,
    },
    {
        id: 2,
        name: "Ben ",
        src: '/images/testimonial/client-img-3-2.png',
        position: "Businessman",
        review: "The Themeix team were awesome helping with my custom Ghost blog theme, they listened to all my suggestions and implemented them fantastically. Any changes and fine tuning was done very quickly. ",
        rating: 5,
    },
    {
        id: 3,
        name: "Kwan Eschmann",
        src: '/images/testimonial/client-img-3-3.png',
        position: "Businessman",
        review: "One of the best customer services out there. Very attentive and fast turnaround. The theme is nice and not too complicated for the non-tech-savvy to work around.",
        title:"Customer Service",
        rating: 4,
    },
    {
        id: 4,
        name: "James Mason",
        src: '/images/testimonial/client-img-3-4.png',
        position: "Businessman",
        review: "I cannot fault this company. They have really helped me and gone above and beyond to configure my theme as I want it. Everything I have asked for has been delivered within a short time frame. I can honestly say, this is some of the best customer service I've ever experienced.",
        title:"Code quality",
        rating: 5,
    },
    {
        id: 5,
        name: "Kirils",
        src: '/images/testimonial/client-img-3-5.png',
        position: "Businessman",
        review: "Themeix team did a Ghost theme customization for us - everything went better and smoother than expected. Great communication, they respond promptly and understand customer's needs.",
        rating: 5,
    },
    {
        id: 6,
        name: "Mildly Opinionated ",
        src: '/images/testimonial/client-img-3-6.png',
        position: "Blogger",
        review: "Themeix has always been there to answer questions and provide detailed and thorough tech support on my Ghost site using their theme. They answer chats and tickets with equal professionalism. Great Ghost theme provider!",
        title:"Customer Support",
        rating: 5,
    },
   
]